backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin
    - editor

media_folder: "static/images/uploads"
public_folder: "/images/uploads" 

collections:
  - name: "pages"
    label: "Shop Info and Gallery intro"
    files:
      - file: "content/shop.md"
        label: "Shop Info"
        name: "shop"
        create: false
        fields:
          - {label: "tagline", name: "tagline", widget: "string"}
          - {label: "street address", name: "streetAddress", widget: "string"}
          - {label: "phone number", name: "phone", widget: "string"}
          - {label: "opening time: weekdays", name: "weekdayOpen", widget: "string"}
          - {label: "closing time: weekdays", name: "weekdayClose", widget: "string"}
          - {label: "opening time: Saturday", name: "saturdayOpen", widget: "string"}
          - {label: "closing time: weekdays", name: "saturdayOpen", widget: "string"}
          - {label: "type", name: "type", widget: "hidden"}
      - file: "content/gallery/_index.md"
        label: "Gallery Page intro paragraph"
        name: "gallery"
        create: false
        fields:
          - {label: "Body", name: "body", widget: "markdown"} 

    - name: "services"
      label: "Services and Pricing"
      folder: "content/services"
      create: true
      fields:
        - {label: "service", name: "service", widget: "string"}
        - {label: "price (include '$' before number )", name: "price", widget: "string"}
        - {label: "order", name: "weight", widget: "number"}
        - {label: "type", name: "type", widget: "hidden", default: "service"}

    - name: "gallery"
      label: "Gallery"
      folder: "content/gallery"
      create: true
      fields:
        - {label: "image title", name: "title", widget: "string"}
        - {label: "thumbnail image (200px wide x 195px high)", name: "thumbnail", widget: "image"}
        - {label: "full-page image", name: "image", widget: "image"}
        - {label: "description", name: "description", widget: "text"}
        - {label: "order", name: "weight", widget: "number"}

