backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin
    - editor

media_folder: "static/images/uploads"
public_folder: "/images/uploads" 

collections:

  - label: "Shop Info and Gallery intro"
    name: "pages"
    files:
      - file: "content/shop.md"
        label: "Shop Info"
        name: "shop"
        create: false
        fields:
          - {label: "tagline", name: "tagline", widget: "string"}
          - {label: "home-page image", name: "image", widget: "image"}          
          - {label: "Home-page text", name: "body", widget: "markdown"}
          - {label: "street address", name: "streetAddress", widget: "string"}
          - {label: "phone number", name: "phone", widget: "string"}
          - {label: "days open (weekdays)", name: "daysOpen", widget: "string"}
          - {label: "opening time: weekdays", name: "weekdayOpenTime", widget: "string"}
          - {label: "closing time: weekdays", name: "weekdayCloseTime", widget: "string"}
          - {label: "opening time: Saturday", name: "saturdayOpenTime", widget: "string"}
          - {label: "closing time: Saturday", name: "saturdayCloseTime", widget: "string"}
          - {label: "days closed", name: "daysClosed", widget: "string"}           
          - {label: "type", name: "type", widget: "hidden"}
      - file: "content/gallery-intro.md"
        label: "Gallery Page intro and photo credits"
        name: "gallery-intro"
        create: false
        fields:
          - {label: "Intro paragraph", name: "intro", widget: "text"}
          - {label: "Photo credits", name: "credits", widget: "string"}
          - {label: "type", name: "type", widget: "hidden"}

  - label: "Services and Pricing"
    name: "services"
    folder: "content/services"
    create: true
    fields:
      - {label: "service", name: "title", widget: "string"}
      - {label: "price", name: "price", widget: "string"}
      - {label: "order", name: "weight", widget: "number"}
      - {label: "type", name: "type", widget: "hidden", default: "service"}

  - label: "Gallery"
    name: "gallery"
    folder: "content/gallery"
    create: true
    fields:
      - {label: "image title (pops up over thumbnail)", name: "title", widget: "string"}
      - {label: "thumbnail image (200px wide x 195px high)", name: "thumbnail", widget: "image"}
      - {label: "full-page image (max width: 1100px | max height 750px)", name: "image", widget: "image"}
      - {label: "description (caption under large picture)", name: "description", widget: "text"}
      - {label: "order", name: "weight", widget: "number"}
      - {label: "type", name: "type", widget: "hidden", default: "gallery"}



